---
# tasks file for ansible

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'installed'
  with_items: '{{ ansible_role_required_packages }}'
  tags:
    - ansible
#
- name: Install pip packages
  pip:
    name: '{{ item.name }}'
    version: '{{ item.version|d(omit) }}'
  with_items: '{{ ansible_role_pip_package + ansible_role_extra_pip_packages }}'
  tags:
    - ansible
